# SPDX-FileCopyrightText: 2024 - 2025 NRK
#
# SPDX-License-Identifier: MIT

version = 1
SPDX-PackageName = "terraform-registry"
SPDX-PackageSupplier = "Stig Otnes Kolstad <stig.otnes.kolstad@nrk.no>"
SPDX-PackageDownloadLocation = "https://github.com/nrkno/terraform-registry"
annotations = []
